### ISSUE TITLE
Icons in use in next

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-icons#11]
The following icons are in use in next and need importing to o-icons so we can deprecate the nextIcon mixin. Can those I've assigned below please work with the origami team to provide copies of the SVGs etc.
- [x] [gift](https://github.com/Financial-Times/n-email-article/blob/master/components/gift-or-not-selection.scss#L15) @bjfletcher (https://github.com/Financial-Times/n-email-article/pull/11)
- [x] [Various publication-type icons](https://github.com/Financial-Times/n-barriers/blob/master/scss/components/product-selector/main.scss#L253-275) @lc512k @ifyio @tavvy (https://github.com/Financial-Times/n-barriers/pull/9)
- [x] [video](https://github.com/Financial-Times/next-card/blob/master/src/scss/_standard.scss#L191) @i-like-robots (https://github.com/Financial-Times/n-card/pull/94)
- [x] [star hollow] https://github.com/Financial-Times/n-message-prompts/blob/ce939d9577283b3c9a8ab91e0ea4d8080d32a233/src/prompts/styles/promo-unit.scss#L289 @ifyio - https://github.com/Financial-Times/n-message-prompts/pull/90
- [x] brand-ft-masthead, myft-bolder, brand-ft, brand-fast https://github.com/Financial-Times/next-front-page/blob/5072415def21f7114fcdd9d2e18c8420d9e103df/shared/components/fast-ft/_fast-ft.scss   - @wheresrhys to migrate away from reliance on nextIcon()

cc @AlbertoElias @onishiweb

**Comment by bjfletcher** [comment]
@wheresrhys sorry - what exactly do you want me to do here?

**Comment by wheresrhys** [comment]
The icon you made for gift article needs to go in to o-icons and code in next that uses nextIcon needs to be updated to use o-icons, so a PR to o-icons and then changes in the article app to remove the dependency on nextIcons

**Comment by bjfletcher** [comment]
@wheresrhys Ok, great. Let's say I have this:

`@include nextIcon(arrow-left, getColorFor('link', 'text'), 15);`

what should I replace it with?

**Comment by wheresrhys** [comment]
nothing yet, you need to get the gift icon into the o-icons font set first

**Comment by bjfletcher** [comment]
Ok, @wheresrhys, is this what you guys wanted?

Gift: https://github.com/Financial-Times/o-ft-icons/blob/master/svg/gift.svg

**Comment by onishiweb** [comment]
Thanks @bjfletcher, have opened #12 to add the gift icon to the set.

**Comment by bjfletcher** [comment]
@onishiweb Great, thanks :) Let me know if there's anything more you need from me @wheresrhys :+1:

**Comment by wheresrhys** [comment]
For the benefit of everyone tagged above, the process should be
1. Open a PR to submit the SVG[s] of the icon you're using to o-icons
2. Once that's merged and released replace any uses of nextIcon with something like `@include oIconsGetIcon('plus', oColorsGetPaletteColor('cold-1'), 32);` - it's an almost identiacl API to `nextIcon()`

**Comment by tavvy** [comment]
could someone provide me with permissions for this repo please?

edit: permissions granted. PR opened

**Comment by wheresrhys** [comment]
The 4th point above (assigned to me) I will raise as an issue in n-ui. It's dependent on fastft being added to the logo-images repo (@aelias is aware of this) but needn't block this issue

**Comment by AlbertoElias** [comment]
@sarahhornsey is looking into getting the logo

**Comment by ironsidevsquincy** [comment]
All done, I'll close once the new icon set has been deployed to the image service (should be Monday)
