### ISSUE TITLE
Multi-coloured icons

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-icons#22]
Given next's two-tone icons (e.g. the fancy quote marks) & the migration of the image service to a new provider, is now an appropriate time to look at supporting multi-coloured icons? The current implementation of these fancy icons (create multiple elements/pseudo-elements, and carefully overlap them with CSS) is suboptimal from performance, dev workflow, reliability and extensibility points of view

For now the implementation of icons is more or less: 

> start with an svg that defines no colours and use a regex to add a `fill` attribute to each path. 

Could this be expanded to: 

> start with an svg with placeholder fill attributes e.g. `fill="{primary-colour}"` and use a more sophisticated string replacement system

Problems to think about
- backwards compatibility - although these multi-tonal icons would all be new, so it wouldn't necessarily entail changes to existing icons, it'd be nice to be able to update existing icons to the same syntax
- documentation/standardisation - each multi-tonal icon would effectively have its own API... where and how to document it??
- how does this fit in with proposed replacements for the image service?

@i-like-robots @alicebartlett @rowanmanning

**Comment by rowanmanning** [comment]
Fancy having a quick chat about this some time today, Rhys? It so happens that I'm about to look at SVG colouring.

**Comment by alicebartlett** [comment]
I think this is a question that starts with talking to Sue Vago.
