### ISSUE TITLE
Any reason this repo has a package.json?

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-icons#62]
Any reason this repo has a package.json?

**Comment by JakeChampion** [comment]
Legacy reasons, this project used to have it's own development dependencies. It used Grunt first of all, then moved to Gulp and now has no dependencies at all.

**Comment by jamesnicholls** [comment]
So can the package.json be removed?

**Comment by JakeChampion** [comment]
Done in #63

**Comment by jamesnicholls** [comment]
Thanks!
