### ISSUE TITLE
Improve registry demos for o-icons

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-icons#83]
Currently we do not point towards the fticons imageset and so developers can get stuck trying to figure out what icons are available in the o-icons component.

Perhaps we should have a demo which uses every single icon?

**Comment by notlee** [comment]
💯 💯 💯 💯

**Comment by chee** [comment]
https://rizzo.lonelyplanet.com/styleguide/design-elements/interface-icons

**Comment by notlee** [comment]
This is done, to be released as part of the major cascade https://github.com/Financial-Times/o-icons/pull/89
